# Generated by Django 2.0.6 on 2018-07-27 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20180726_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='xp',
            field=models.IntegerField(default=0),
        ),
    ]
